# Generated by Django 3.2.18 on 2023-07-23 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(auto_created=True, max_length=5, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(auto_created=True, max_length=5, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('job_desc', models.TextField(max_length=500)),
                ('job_starting', models.DateTimeField(default=None)),
                ('job_ending', models.DateTimeField(default=None)),
                ('job_status', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobStarting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField(default=datetime.datetime.now)),
                ('s_name', models.TextField(max_length=100)),
                ('s_jobs', models.TextField(max_length=100)),
                ('s_start', models.DateTimeField(default=datetime.datetime.now)),
                ('s_end', models.DateTimeField(default=datetime.datetime.now)),
                ('s_status', models.TextField(max_length=200)),
                ('s_lunch', models.CharField(max_length=3)),
                ('s_holyday', models.CharField(max_length=3)),
            ],
        ),
    ]
