# Generated by Django 3.2.18 on 2023-07-24 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstarting',
            name='s_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='jobstarting',
            name='s_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
